### ISSUE TITLE
How to run the cli

### ISSUE THREAD

**Issue by alexef** [laszlocph/woodpecker#156]
Is there a binary download option for the CLI, or a docker image?

**Comment by laszlocph** [comment]
https://github.com/laszlocph/woodpecker/releases/tag/v0.13.0-rc.1

Let me know how you are getting on!

**Comment by alexef** [comment]
thank you for the quick response!

we're currently running drone 0.8 and considering switching over to woodpecker (~200 users / ~300 private github repos). so far we couldn't find any blocker for the upgrade, is there anything we should keep in mind?

**Comment by laszlocph** [comment]
I have news from a comparable sized deployment: 30 users / 200 repos and 500-1000 builds a week. It should be a drop in replacement.

The risk I'm seeing with Woodpecker today is keeping the dependencies up to date and testing all features that Drone 0.8 has. Especially on the fringes of non Github usage (Gitea, etc which I don't use).

So it should work, but best to test it yourself. Which I sense you already did.

I really hope it will work out for you. Otherwise just open a ticket with any finding you have.
